ReadSignalsWithLimit added, no API breakage
starfederation/datastar pull request #397
Opened 2024-12-18 09:07 UTC by iansmith

I wanted to limit the size of uploads because file uploads of unlimited size are an attack vector.  I also wanted to control the size from user code because I need to allow users to upload several large images at once.

`ReadSignalsWithLimit` is now the implementation of `ReadSignals` where it uses a default max size.  I also added and error that folks can check for if they want to detect this situation in user code.

2024-12-18 15:55 UTC, delaneyj requested changes
Like the idea, needs to be changed to an options API, something like

```go
 ReadSignals(r *http.Request, signals any, opts ...ReadOption) error
 ```

2024-12-26 16:41 UTC, bencroker commented
@iansmith any update on this?

2025-01-01 23:24 UTC, delaneyj commented
?

2025-01-14 01:08 UTC, delaneyj commented
Please reopen when you make the changes per request above

2025-01-14 01:08 UTC, closed without merging